apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgB5Bk+cGCz+GrsPBc9xvoEYRTpBLvL6dZWxBotcSRV0piyYqMweNazkpyULCBl8sysvHoBqNBdEdPNk+amfBCB/sF535ZOTccP0ItVYV6pRnUjXqbE6NzM89tyZNnzZ5+eQLqHSm+3FuDJ8ONMPo7OxzClFTPkfNQARn9IIjFO8Jhf1puKa4F1Yxp9P/HDcmIVmKQipiK0ilCyJ+T8hrh5V+Dg1RvgZ+0oV8HD7PnutNZEdieU2pF6Reak5PQgp7HCqLet/akEDW2WXzAnSpgCSUYSZoxM6nCrk49OR2miBkpvhC2mSBaouHZRLS52kzzznI04KFvpAaOU8OR01uQlNH/wNi6RwsZu9N6a6ng09j5z+rtFu7mvsAVkG9xRyFH+/F41IXWB9GNo7vWhmGxpuupqUMjUgmVzrIwUKotZ1emUHh5bFkxkOG9kLSt2K1bg3Fl1a51yWSUWf6Hj1Yd00psV0ZOF0mbyV3AbPD9QvNN0ir76YkmQodwtjfpAf0TS7ndNJAWQt7nGPs26ummW67urYiGHU/AuSIFqcLl31DIWClI/Ed4nOyzOhWjPBMBp/sWpWvj2Pvr3cdKk5pABLIw15QH0qAoZOZT8/1fpVw88S1Wa1WngtnrOfPodzcluaeYcYdkfr9WkoM4v+QbHeMjHIvPD0tnUg2avKftmGKVrAzj+MTHjY3A/cOLd/eZIe/U+a9/qVFwZtexjGNJk921mYeMMi2qyu27W991R6G+B30QuMivuUAHrxeXSTtiZ62vht2g==
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

