apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBYlOOizfoJStKw9VQxQrwDAyzS+YzawSgbgyKBqLzMC8ujp0BlCnb1mz8mAuM2Er3h8DcgjCkteo8hhehVijr3aV99wZ4hhaO/u25oDzYGfwyqVy81RsXnKZ6g0exwemQX+/f27T7GT4/kXF17Ev6Wyqlv6dEwVMMgL+BMPKpfDO/MCazvNSNg9gN48nrAUmThEklZDuCpXCdrU8ggan6pAWsF770LqDxodaBpVTjwbQnOkxafjh8YryQ1qi3we182XEqeFScZio6rXpiM9Xglx7kartP0QZG8CU62gWk02Vzw/FG+XAGrtTQZMMU1YurB+lOtn1ypB/jzTKOwxB/pRXWe7JbLr4paz8CzRwpHIy3cGVcbFVT/lEMSfLk94Qsb34TNvrvCEW/YOfcVhw5ohy7WamDEcVbdAH06pJKo1nSAzDfbb9PIx5G/N9LJ2g/WXH2b42Vrc2MHUhJTFnNK6h4vRWW5p8fo05SPJzNiGYQOmDbG7TCgmln9SsqZ+Fzqr2DrWGAZHC1+/bwBmG/rbPyXTU3WtokszGD9LrVqg4JQReKCXbC0WkjPk035VZWsfvTelVRIVIzjdKcVmzvbVN0655xQb37PSiUS+PzjpOwIo85a3awMk9OnTyZ8ZB2bD8KajX60Xkb+7DpYbn0Yb6B3QTJZKoboxUx4lBerWVT67cE6Ig9Q840e321CoxxnNfPjqi1lIYB926V/sHJktdH1Gq1testgQTl0yn1kj8G14zvRCZiFebKXPOcKguUJtG4tAg==

